# Welcome to Jekyll!
#


title: The Working Dev
email: tedhagos@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A coding journal by Ted Hagos. Practical tutorials on Java, Kotlin, and 
  Android, now expanding into defensive coding and AI-assisted development 
  workflows. Grounded insights for the pragmatic programmer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: lovescaffeine

github_username:  tedhagos
twitter:
  username: lovescaffeine
  card: summary


author:
  name: Ted Hagos
  url: https://tedhagos.com
  twitter: lovescaffeine
  description: CTO, author of 8 Apress books, and technical educator.
  links:
    - https://www.amazon.com/author/tedhagos
    - https://twitter.com/lovescaffeine


url: "https://workingdev.net" # the base hostname & protocol for your site

# Build settings
theme: minima
default_image: /images/gandalf-programmer.jpg

markdown: kramdown

show_excerpts: true
google_analytics: UA-123410395-1


defaults:
  layout: post
  author: "Ted Hagos"


